### ISSUE TITLE
他人のタスクを消去することができてしまう

### ISSUE THREAD

**Issue by Nemurino-kai** [kohei-kohei/ToDoList#1]
## 発生している問題
hiddenパラメータであるidを変更して完了を行うことで、他人のアカウントにログインせずとも、他人のタスクを消すことが可能です。

**Comment by kohei-kohei** [comment]
それはデモページ上でですよね？
具体的にどういった攻撃をしていますか？

**Comment by Nemurino-kai** [comment]
デモページ上の、タスクが表示されている部分
``` html

</li><li class="flex"><p>136番</p>
  <form action="index.php" method="post">
   <input type="hidden" name="method" value="put">
   <input type="hidden" name="id" value="136">
    
   <input type="hidden" name="token" value="(トークンが入る)">
  <button type="submit">完了</button>
  </form>
   </li>
```
において、idを書き換えて完了を行うと、他のタスクも消すことができます。
hiddenパラメータですが、ユーザ側で書き換えることは可能です。
idは連番で与えられているので、例えば1～135をidとして指定すれば、すべてのタスクを消すことができてしまいます。
ログインした本人でないと、消せないようにすべきと考えます。

**Comment by kohei-kohei** [comment]
確かにそうですね。。。
ご指摘ありがとうございます。
修正します。

**Comment by kohei-kohei** [comment]
修正致しました。
どうでしょうか？

**Comment by Nemurino-kai** [comment]
OK! user名チェック機能してます。解決したのでcloseします。
